from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from models import DriverProfile, Facility, Objective, PortLink, ScenarioPreset, Vehicle


FACILITY_SEEDS = [
    {
        "name": "Bhopal Distribution Reserve",
        "city": "Bhopal",
        "facility_type": "warehouse",
        "latitude": 23.2599,
        "longitude": 77.4126,
        "base_capacity_units": 9000,
        "initial_inventory_units": 3600,
        "current_inventory_units": 3600,
        "queue_capacity_units": 1800,
    },
    {
        "name": "Lucknow Regional Depot",
        "city": "Lucknow",
        "facility_type": "warehouse",
        "latitude": 26.8467,
        "longitude": 80.9462,
        "base_capacity_units": 8500,
        "initial_inventory_units": 3400,
        "current_inventory_units": 3400,
        "queue_capacity_units": 1700,
    },
    {
        "name": "Kanpur Logistics Hub",
        "city": "Kanpur",
        "facility_type": "warehouse",
        "latitude": 26.4499,
        "longitude": 80.3319,
        "base_capacity_units": 7800,
        "initial_inventory_units": 3120,
        "current_inventory_units": 3120,
        "queue_capacity_units": 1560,
    },
    {
        "name": "Patna Emergency Store",
        "city": "Patna",
        "facility_type": "warehouse",
        "latitude": 25.5941,
        "longitude": 85.1376,
        "base_capacity_units": 8200,
        "initial_inventory_units": 3280,
        "current_inventory_units": 3280,
        "queue_capacity_units": 1640,
    },
    {
        "name": "Ranchi Aid Center",
        "city": "Ranchi",
        "facility_type": "warehouse",
        "latitude": 23.3441,
        "longitude": 85.3096,
        "base_capacity_units": 7500,
        "initial_inventory_units": 3000,
        "current_inventory_units": 3000,
        "queue_capacity_units": 1500,
    },
    {
        "name": "Raipur Supply Node",
        "city": "Raipur",
        "facility_type": "warehouse",
        "latitude": 21.2514,
        "longitude": 81.6296,
        "base_capacity_units": 8900,
        "initial_inventory_units": 3560,
        "current_inventory_units": 3560,
        "queue_capacity_units": 1780,
    },
    {
        "name": "Bhubaneswar Food Buffer",
        "city": "Bhubaneswar",
        "facility_type": "warehouse",
        "latitude": 20.2961,
        "longitude": 85.8245,
        "base_capacity_units": 9400,
        "initial_inventory_units": 3760,
        "current_inventory_units": 3760,
        "queue_capacity_units": 1880,
    },
    {
        "name": "Guwahati Northeast Hub",
        "city": "Guwahati",
        "facility_type": "warehouse",
        "latitude": 26.1445,
        "longitude": 91.7362,
        "base_capacity_units": 9000,
        "initial_inventory_units": 3600,
        "current_inventory_units": 3600,
        "queue_capacity_units": 1800,
    },
    {
        "name": "Srinagar Hill Reserve",
        "city": "Srinagar",
        "facility_type": "warehouse",
        "latitude": 34.0837,
        "longitude": 74.7973,
        "base_capacity_units": 6500,
        "initial_inventory_units": 2600,
        "current_inventory_units": 2600,
        "queue_capacity_units": 1300,
    },
    {
        "name": "Chandigarh Northern Gateway",
        "city": "Chandigarh",
        "facility_type": "warehouse",
        "latitude": 30.7333,
        "longitude": 76.7794,
        "base_capacity_units": 8700,
        "initial_inventory_units": 3480,
        "current_inventory_units": 3480,
        "queue_capacity_units": 1740,
    },
    {
        "name": "Dehradun Supply Base",
        "city": "Dehradun",
        "facility_type": "warehouse",
        "latitude": 30.3165,
        "longitude": 78.0322,
        "base_capacity_units": 7200,
        "initial_inventory_units": 2880,
        "current_inventory_units": 2880,
        "queue_capacity_units": 1440,
    },
    {
        "name": "Ludhiana Industrial Depot",
        "city": "Ludhiana",
        "facility_type": "warehouse",
        "latitude": 30.901,
        "longitude": 75.8573,
        "base_capacity_units": 9100,
        "initial_inventory_units": 3640,
        "current_inventory_units": 3640,
        "queue_capacity_units": 1820,
    },
    {
        "name": "Amritsar Border Facility",
        "city": "Amritsar",
        "facility_type": "warehouse",
        "latitude": 31.634,
        "longitude": 74.8723,
        "base_capacity_units": 7600,
        "initial_inventory_units": 3040,
        "current_inventory_units": 3040,
        "queue_capacity_units": 1520,
    },
    {
        "name": "Jodhpur Arid Buffer",
        "city": "Jodhpur",
        "facility_type": "warehouse",
        "latitude": 26.2389,
        "longitude": 73.0243,
        "base_capacity_units": 7900,
        "initial_inventory_units": 3160,
        "current_inventory_units": 3160,
        "queue_capacity_units": 1580,
    },
    {
        "name": "Udaipur Transfer Point",
        "city": "Udaipur",
        "facility_type": "warehouse",
        "latitude": 24.5854,
        "longitude": 73.7125,
        "base_capacity_units": 7400,
        "initial_inventory_units": 2960,
        "current_inventory_units": 2960,
        "queue_capacity_units": 1480,
    },
    {
        "name": "Bikaner Sand Area Store",
        "city": "Bikaner",
        "facility_type": "warehouse",
        "latitude": 28.0229,
        "longitude": 73.3119,
        "base_capacity_units": 7000,
        "initial_inventory_units": 2800,
        "current_inventory_units": 2800,
        "queue_capacity_units": 1400,
    },
    {
        "name": "Rajkot Coastal Backup",
        "city": "Rajkot",
        "facility_type": "warehouse",
        "latitude": 22.3039,
        "longitude": 70.8022,
        "base_capacity_units": 8300,
        "initial_inventory_units": 3320,
        "current_inventory_units": 3320,
        "queue_capacity_units": 1660,
    },
    {
        "name": "Vadodara Transit Hub",
        "city": "Vadodara",
        "facility_type": "warehouse",
        "latitude": 22.3072,
        "longitude": 73.1812,
        "base_capacity_units": 8900,
        "initial_inventory_units": 3560,
        "current_inventory_units": 3560,
        "queue_capacity_units": 1780,
    },
    {
        "name": "Nashik Central Support",
        "city": "Nashik",
        "facility_type": "warehouse",
        "latitude": 20.011,
        "longitude": 73.7903,
        "base_capacity_units": 8200,
        "initial_inventory_units": 3280,
        "current_inventory_units": 3280,
        "queue_capacity_units": 1640,
    },
    {
        "name": "Aurangabad Midpoint Center",
        "city": "Aurangabad",
        "facility_type": "warehouse",
        "latitude": 19.8762,
        "longitude": 75.3433,
        "base_capacity_units": 7800,
        "initial_inventory_units": 3120,
        "current_inventory_units": 3120,
        "queue_capacity_units": 1560,
    },
    {
        "name": "Solapur Transit Base",
        "city": "Solapur",
        "facility_type": "warehouse",
        "latitude": 17.6599,
        "longitude": 75.9064,
        "base_capacity_units": 7500,
        "initial_inventory_units": 3000,
        "current_inventory_units": 3000,
        "queue_capacity_units": 1500,
    },
    {
        "name": "Kolhapur South Connect",
        "city": "Kolhapur",
        "facility_type": "warehouse",
        "latitude": 16.705,
        "longitude": 74.2433,
        "base_capacity_units": 7700,
        "initial_inventory_units": 3080,
        "current_inventory_units": 3080,
        "queue_capacity_units": 1540,
    },
    {
        "name": "Hubli Cargo Relay",
        "city": "Hubli",
        "facility_type": "warehouse",
        "latitude": 15.3647,
        "longitude": 75.124,
        "base_capacity_units": 8400,
        "initial_inventory_units": 3360,
        "current_inventory_units": 3360,
        "queue_capacity_units": 1680,
    },
    {
        "name": "Mangaluru Coastal Port",
        "city": "Mangaluru",
        "facility_type": "port",
        "latitude": 12.9141,
        "longitude": 74.856,
        "base_capacity_units": 12000,
        "initial_inventory_units": 4800,
        "current_inventory_units": 4800,
        "queue_capacity_units": 2400,
    },
    {
        "name": "Mysuru Southern Depot",
        "city": "Mysuru",
        "facility_type": "warehouse",
        "latitude": 12.2958,
        "longitude": 76.6394,
        "base_capacity_units": 8100,
        "initial_inventory_units": 3240,
        "current_inventory_units": 3240,
        "queue_capacity_units": 1620,
    },
    {
        "name": "Madurai Inner Station",
        "city": "Madurai",
        "facility_type": "warehouse",
        "latitude": 9.9252,
        "longitude": 78.1198,
        "base_capacity_units": 7900,
        "initial_inventory_units": 3160,
        "current_inventory_units": 3160,
        "queue_capacity_units": 1580,
    },
    {
        "name": "Tiruchirappalli Crossroads",
        "city": "Tiruchirappalli",
        "facility_type": "warehouse",
        "latitude": 10.7905,
        "longitude": 78.7047,
        "base_capacity_units": 8300,
        "initial_inventory_units": 3320,
        "current_inventory_units": 3320,
        "queue_capacity_units": 1660,
    },
    {
        "name": "Thiruvananthapuram Southern Terminal",
        "city": "Thiruvananthapuram",
        "facility_type": "warehouse",
        "latitude": 8.5241,
        "longitude": 76.9366,
        "base_capacity_units": 8800,
        "initial_inventory_units": 3520,
        "current_inventory_units": 3520,
        "queue_capacity_units": 1760,
    },
    {
        "name": "Kochi Gateway Port",
        "city": "Kochi",
        "facility_type": "port",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "base_capacity_units": 13500,
        "initial_inventory_units": 5400,
        "current_inventory_units": 5400,
        "queue_capacity_units": 2700,
    },
    {
        "name": "Visakhapatnam Deepwater Port",
        "city": "Visakhapatnam",
        "facility_type": "port",
        "latitude": 17.6868,
        "longitude": 83.2185,
        "base_capacity_units": 15500,
        "initial_inventory_units": 6200,
        "current_inventory_units": 6200,
        "queue_capacity_units": 3100,
    },
    {
        "name": "Paradip Freight Port",
        "city": "Paradip",
        "facility_type": "port",
        "latitude": 20.2647,
        "longitude": 86.6669,
        "base_capacity_units": 14000,
        "initial_inventory_units": 5600,
        "current_inventory_units": 5600,
        "queue_capacity_units": 2800,
    },
    {
        "name": "Tuticorin Marine Port",
        "city": "Tuticorin",
        "facility_type": "port",
        "latitude": 8.7642,
        "longitude": 78.1348,
        "base_capacity_units": 12500,
        "initial_inventory_units": 5000,
        "current_inventory_units": 5000,
        "queue_capacity_units": 2500,
    },
    {
        "name": "Kandla Export Port",
        "city": "Kandla",
        "facility_type": "port",
        "latitude": 23.0033,
        "longitude": 70.2227,
        "base_capacity_units": 14800,
        "initial_inventory_units": 5920,
        "current_inventory_units": 5920,
        "queue_capacity_units": 2960,
    },
    {
        "name": "Mormugao Bulk Port",
        "city": "Goa",
        "facility_type": "port",
        "latitude": 15.405,
        "longitude": 73.7933,
        "base_capacity_units": 11500,
        "initial_inventory_units": 4600,
        "current_inventory_units": 4600,
        "queue_capacity_units": 2300,
    },
    {
        "name": "Delhi National Medical Reserve",
        "city": "Delhi",
        "facility_type": "warehouse",
        "latitude": 28.6139,
        "longitude": 77.2090,
        "base_capacity_units": 10000,
        "initial_inventory_units": 4200,
        "current_inventory_units": 4200,
        "queue_capacity_units": 1800,
    },
    {
        "name": "Jaipur Relief Consolidation Hub",
        "city": "Jaipur",
        "facility_type": "warehouse",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "base_capacity_units": 9000,
        "initial_inventory_units": 3100,
        "current_inventory_units": 3100,
        "queue_capacity_units": 1200,
    },
    {
        "name": "Ahmedabad Vaccine Cold Store",
        "city": "Ahmedabad",
        "facility_type": "warehouse",
        "latitude": 23.0225,
        "longitude": 72.5714,
        "base_capacity_units": 9500,
        "initial_inventory_units": 3300,
        "current_inventory_units": 3300,
        "queue_capacity_units": 1500,
    },
    {
        "name": "Mumbai Coastal Relief Warehouse",
        "city": "Mumbai",
        "facility_type": "warehouse",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "base_capacity_units": 12000,
        "initial_inventory_units": 7200,
        "current_inventory_units": 7200,
        "queue_capacity_units": 2000,
    },
    {
        "name": "Pune Oxygen Buffer Center",
        "city": "Pune",
        "facility_type": "warehouse",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "base_capacity_units": 8600,
        "initial_inventory_units": 2800,
        "current_inventory_units": 2800,
        "queue_capacity_units": 1100,
    },
    {
        "name": "Nagpur Central Emergency Depot",
        "city": "Nagpur",
        "facility_type": "warehouse",
        "latitude": 21.1458,
        "longitude": 79.0882,
        "base_capacity_units": 8300,
        "initial_inventory_units": 2900,
        "current_inventory_units": 2900,
        "queue_capacity_units": 1400,
    },
    {
        "name": "Hyderabad Health Supply Connector",
        "city": "Hyderabad",
        "facility_type": "warehouse",
        "latitude": 17.3850,
        "longitude": 78.4867,
        "base_capacity_units": 9300,
        "initial_inventory_units": 3600,
        "current_inventory_units": 3600,
        "queue_capacity_units": 1500,
    },
    {
        "name": "Hosur Mobility Support Hub",
        "city": "Hosur",
        "facility_type": "warehouse",
        "latitude": 12.7409,
        "longitude": 77.8253,
        "base_capacity_units": 7400,
        "initial_inventory_units": 2500,
        "current_inventory_units": 2500,
        "queue_capacity_units": 900,
    },
    {
        "name": "Bengaluru Emergency Distribution Campus",
        "city": "Bengaluru",
        "facility_type": "warehouse",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "base_capacity_units": 11000,
        "initial_inventory_units": 4300,
        "current_inventory_units": 4300,
        "queue_capacity_units": 1900,
    },
    {
        "name": "Chennai Public Health Warehouse",
        "city": "Chennai",
        "facility_type": "warehouse",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "base_capacity_units": 12500,
        "initial_inventory_units": 8100,
        "current_inventory_units": 8100,
        "queue_capacity_units": 2200,
    },
    {
        "name": "Coimbatore Nutrition Support Terminal",
        "city": "Coimbatore",
        "facility_type": "warehouse",
        "latitude": 11.0168,
        "longitude": 76.9558,
        "base_capacity_units": 7200,
        "initial_inventory_units": 2200,
        "current_inventory_units": 2200,
        "queue_capacity_units": 900,
    },
    {
        "name": "Kolkata Humanitarian Gateway",
        "city": "Kolkata",
        "facility_type": "warehouse",
        "latitude": 22.5726,
        "longitude": 88.3639,
        "base_capacity_units": 9800,
        "initial_inventory_units": 3400,
        "current_inventory_units": 3400,
        "queue_capacity_units": 1600,
    },
    {
        "name": "Surat Community Food Reserve",
        "city": "Surat",
        "facility_type": "warehouse",
        "latitude": 21.1702,
        "longitude": 72.8311,
        "base_capacity_units": 7600,
        "initial_inventory_units": 2600,
        "current_inventory_units": 2600,
        "queue_capacity_units": 1000,
    },
    {
        "name": "Indore District Response Yard",
        "city": "Indore",
        "facility_type": "warehouse",
        "latitude": 22.7196,
        "longitude": 75.8577,
        "base_capacity_units": 8200,
        "initial_inventory_units": 2700,
        "current_inventory_units": 2700,
        "queue_capacity_units": 1000,
    },
    {
        "name": "Kharagpur Rail Relief Buffer",
        "city": "Kharagpur",
        "facility_type": "warehouse",
        "latitude": 22.3460,
        "longitude": 87.2319,
        "base_capacity_units": 7800,
        "initial_inventory_units": 2400,
        "current_inventory_units": 2400,
        "queue_capacity_units": 1000,
    },
    {
        "name": "Chennai Humanitarian Port",
        "city": "Chennai",
        "facility_type": "port",
        "latitude": 13.1067,
        "longitude": 80.3078,
        "base_capacity_units": 15000,
        "initial_inventory_units": 10400,
        "current_inventory_units": 10400,
        "queue_capacity_units": 2500,
    },
    {
        "name": "Mumbai Relief Port Terminal",
        "city": "Mumbai",
        "facility_type": "port",
        "latitude": 18.9493,
        "longitude": 72.8406,
        "base_capacity_units": 16500,
        "initial_inventory_units": 11800,
        "current_inventory_units": 11800,
        "queue_capacity_units": 2800,
    },
    {
        "name": "Kolkata Aid Dock Operations",
        "city": "Kolkata",
        "facility_type": "port",
        "latitude": 22.5340,
        "longitude": 88.2920,
        "base_capacity_units": 14200,
        "initial_inventory_units": 9300,
        "current_inventory_units": 9300,
        "queue_capacity_units": 2000,
    },
    {
        "name": "Surat Coastal Aid Jetty",
        "city": "Surat",
        "facility_type": "port",
        "latitude": 21.0900,
        "longitude": 72.6800,
        "base_capacity_units": 13500,
        "initial_inventory_units": 8600,
        "current_inventory_units": 8600,
        "queue_capacity_units": 1800,
    },
    {
        "name": "Varanasi Distribution Hub",
        "city": "Varanasi",
        "facility_type": "warehouse",
        "latitude": 25.3176,
        "longitude": 83.0062,
        "base_capacity_units": 8800,
        "initial_inventory_units": 3520,
        "current_inventory_units": 3520,
        "queue_capacity_units": 1760,
    },
    {
        "name": "Agra Logistics Depot",
        "city": "Agra",
        "facility_type": "warehouse",
        "latitude": 27.1767,
        "longitude": 78.0081,
        "base_capacity_units": 8500,
        "initial_inventory_units": 3400,
        "current_inventory_units": 3400,
        "queue_capacity_units": 1700,
    },
    {
        "name": "Prayagraj Relief Base",
        "city": "Prayagraj",
        "facility_type": "warehouse",
        "latitude": 25.4358,
        "longitude": 81.8463,
        "base_capacity_units": 7900,
        "initial_inventory_units": 3160,
        "current_inventory_units": 3160,
        "queue_capacity_units": 1580,
    },
    {
        "name": "Jabalpur Central Node",
        "city": "Jabalpur",
        "facility_type": "warehouse",
        "latitude": 23.1815,
        "longitude": 79.9864,
        "base_capacity_units": 8100,
        "initial_inventory_units": 3240,
        "current_inventory_units": 3240,
        "queue_capacity_units": 1620,
    },
    {
        "name": "Gwalior North Connector",
        "city": "Gwalior",
        "facility_type": "warehouse",
        "latitude": 26.2124,
        "longitude": 78.1772,
        "base_capacity_units": 7600,
        "initial_inventory_units": 3040,
        "current_inventory_units": 3040,
        "queue_capacity_units": 1520,
    },
    {
        "name": "Vijayawada Transit Hub",
        "city": "Vijayawada",
        "facility_type": "warehouse",
        "latitude": 16.5062,
        "longitude": 80.6480,
        "base_capacity_units": 9200,
        "initial_inventory_units": 3680,
        "current_inventory_units": 3680,
        "queue_capacity_units": 1840,
    },
    {
        "name": "Nellore Coastal Depot",
        "city": "Nellore",
        "facility_type": "warehouse",
        "latitude": 14.4426,
        "longitude": 79.9865,
        "base_capacity_units": 7400,
        "initial_inventory_units": 2960,
        "current_inventory_units": 2960,
        "queue_capacity_units": 1480,
    },
    {
        "name": "Guntur Agri-Store",
        "city": "Guntur",
        "facility_type": "warehouse",
        "latitude": 16.3067,
        "longitude": 80.4365,
        "base_capacity_units": 8300,
        "initial_inventory_units": 3320,
        "current_inventory_units": 3320,
        "queue_capacity_units": 1660,
    },
    {
        "name": "Warangal Inland Center",
        "city": "Warangal",
        "facility_type": "warehouse",
        "latitude": 17.9689,
        "longitude": 79.5941,
        "base_capacity_units": 7800,
        "initial_inventory_units": 3120,
        "current_inventory_units": 3120,
        "queue_capacity_units": 1560,
    },
    {
        "name": "Kozhikode Western Terminal",
        "city": "Kozhikode",
        "facility_type": "warehouse",
        "latitude": 11.2588,
        "longitude": 75.7804,
        "base_capacity_units": 8600,
        "initial_inventory_units": 3440,
        "current_inventory_units": 3440,
        "queue_capacity_units": 1720,
    },
    {
        "name": "Thrissur Supply Point",
        "city": "Thrissur",
        "facility_type": "warehouse",
        "latitude": 10.5276,
        "longitude": 76.2144,
        "base_capacity_units": 7200,
        "initial_inventory_units": 2880,
        "current_inventory_units": 2880,
        "queue_capacity_units": 1440,
    },
    {
        "name": "Salem Industrial Gateway",
        "city": "Salem",
        "facility_type": "warehouse",
        "latitude": 11.6643,
        "longitude": 78.1460,
        "base_capacity_units": 8900,
        "initial_inventory_units": 3560,
        "current_inventory_units": 3560,
        "queue_capacity_units": 1780,
    },
    {
        "name": "Erode Textile Buffer",
        "city": "Erode",
        "facility_type": "warehouse",
        "latitude": 11.3410,
        "longitude": 77.7172,
        "base_capacity_units": 8000,
        "initial_inventory_units": 3200,
        "current_inventory_units": 3200,
        "queue_capacity_units": 1600,
    },
    {
        "name": "Tiruppur Export Hub",
        "city": "Tiruppur",
        "facility_type": "warehouse",
        "latitude": 11.1085,
        "longitude": 77.3411,
        "base_capacity_units": 9100,
        "initial_inventory_units": 3640,
        "current_inventory_units": 3640,
        "queue_capacity_units": 1820,
    },
    {
        "name": "Belagavi Border Node",
        "city": "Belagavi",
        "facility_type": "warehouse",
        "latitude": 15.8497,
        "longitude": 74.4977,
        "base_capacity_units": 7700,
        "initial_inventory_units": 3080,
        "current_inventory_units": 3080,
        "queue_capacity_units": 1540,
    },
    {
        "name": "Kalaburagi Arid Zone Store",
        "city": "Kalaburagi",
        "facility_type": "warehouse",
        "latitude": 17.3297,
        "longitude": 76.8343,
        "base_capacity_units": 7300,
        "initial_inventory_units": 2920,
        "current_inventory_units": 2920,
        "queue_capacity_units": 1460,
    },
    {
        "name": "Bhavnagar Gulf Depot",
        "city": "Bhavnagar",
        "facility_type": "warehouse",
        "latitude": 21.7645,
        "longitude": 72.1519,
        "base_capacity_units": 8200,
        "initial_inventory_units": 3280,
        "current_inventory_units": 3280,
        "queue_capacity_units": 1640,
    },
    {
        "name": "Jamnagar Petro-Logistics Base",
        "city": "Jamnagar",
        "facility_type": "warehouse",
        "latitude": 22.4707,
        "longitude": 70.0577,
        "base_capacity_units": 9500,
        "initial_inventory_units": 3800,
        "current_inventory_units": 3800,
        "queue_capacity_units": 1900,
    },
    {
        "name": "Dhanbad Mining Relief Center",
        "city": "Dhanbad",
        "facility_type": "warehouse",
        "latitude": 23.7957,
        "longitude": 86.4304,
        "base_capacity_units": 8400,
        "initial_inventory_units": 3360,
        "current_inventory_units": 3360,
        "queue_capacity_units": 1680,
    },
    {
        "name": "Jamshedpur Steel City Depot",
        "city": "Jamshedpur",
        "facility_type": "warehouse",
        "latitude": 22.8046,
        "longitude": 86.2029,
        "base_capacity_units": 9000,
        "initial_inventory_units": 3600,
        "current_inventory_units": 3600,
        "queue_capacity_units": 1800,
    },
    {
        "name": "Asansol Eastern Link",
        "city": "Asansol",
        "facility_type": "warehouse",
        "latitude": 23.6739,
        "longitude": 86.9524,
        "base_capacity_units": 7500,
        "initial_inventory_units": 3000,
        "current_inventory_units": 3000,
        "queue_capacity_units": 1500,
    },
    {
        "name": "Siliguri Northeast Gateway",
        "city": "Siliguri",
        "facility_type": "warehouse",
        "latitude": 26.7271,
        "longitude": 88.3953,
        "base_capacity_units": 8700,
        "initial_inventory_units": 3480,
        "current_inventory_units": 3480,
        "queue_capacity_units": 1740,
    },
    {
        "name": "Agartala Frontier Store",
        "city": "Agartala",
        "facility_type": "warehouse",
        "latitude": 23.8315,
        "longitude": 91.2868,
        "base_capacity_units": 7100,
        "initial_inventory_units": 2840,
        "current_inventory_units": 2840,
        "queue_capacity_units": 1420,
    },
    {
        "name": "Shillong Hill Base",
        "city": "Shillong",
        "facility_type": "warehouse",
        "latitude": 25.5788,
        "longitude": 91.8933,
        "base_capacity_units": 6800,
        "initial_inventory_units": 2720,
        "current_inventory_units": 2720,
        "queue_capacity_units": 1360,
    },
    {
        "name": "Imphal Valley Depot",
        "city": "Imphal",
        "facility_type": "warehouse",
        "latitude": 24.8170,
        "longitude": 93.9368,
        "base_capacity_units": 6500,
        "initial_inventory_units": 2600,
        "current_inventory_units": 2600,
        "queue_capacity_units": 1300,
    },
    {
        "name": "Shimla Mountain Reserve",
        "city": "Shimla",
        "facility_type": "warehouse",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "base_capacity_units": 6200,
        "initial_inventory_units": 2480,
        "current_inventory_units": 2480,
        "queue_capacity_units": 1240,
    },
    {
        "name": "Jammu Northern Terminal",
        "city": "Jammu",
        "facility_type": "warehouse",
        "latitude": 32.7266,
        "longitude": 74.8570,
        "base_capacity_units": 8300,
        "initial_inventory_units": 3320,
        "current_inventory_units": 3320,
        "queue_capacity_units": 1660,
    },
    {
        "name": "Haldia Industrial Port",
        "city": "Haldia",
        "facility_type": "port",
        "latitude": 22.0257,
        "longitude": 88.0583,
        "base_capacity_units": 13800,
        "initial_inventory_units": 5520,
        "current_inventory_units": 5520,
        "queue_capacity_units": 2760,
    },
    {
        "name": "Ennore Container Port",
        "city": "Ennore",
        "facility_type": "port",
        "latitude": 13.2355,
        "longitude": 80.3340,
        "base_capacity_units": 14500,
        "initial_inventory_units": 5800,
        "current_inventory_units": 5800,
        "queue_capacity_units": 2900,
    },
    {
        "name": "Dahej Chemical Port",
        "city": "Dahej",
        "facility_type": "port",
        "latitude": 21.6820,
        "longitude": 72.5859,
        "base_capacity_units": 13200,
        "initial_inventory_units": 5280,
        "current_inventory_units": 5280,
        "queue_capacity_units": 2640,
    },
    {
        "name": "Mundra Mega Port",
        "city": "Mundra",
        "facility_type": "port",
        "latitude": 22.8402,
        "longitude": 69.7063,
        "base_capacity_units": 18000,
        "initial_inventory_units": 7200,
        "current_inventory_units": 7200,
        "queue_capacity_units": 3600,
    },
    {
        "name": "Krishnapatnam Deep Port",
        "city": "Nellore",
        "facility_type": "port",
        "latitude": 14.2504,
        "longitude": 80.1234,
        "base_capacity_units": 14800,
        "initial_inventory_units": 5920,
        "current_inventory_units": 5920,
        "queue_capacity_units": 2960,
    },
    {
        "name": "Pipavav Private Port",
        "city": "Amreli",
        "facility_type": "port",
        "latitude": 20.9167,
        "longitude": 71.5000,
        "base_capacity_units": 12800,
        "initial_inventory_units": 5120,
        "current_inventory_units": 5120,
        "queue_capacity_units": 2560,
    },
]


DRIVER_SEEDS = [
    {"name": "Asha Singh", "override_rating": 1.1, "confidence": 0.74, "accept_recommendation_bias": 0.58},
    {"name": "Vikram Rao", "override_rating": 0.9, "confidence": 0.66, "accept_recommendation_bias": 0.52},
    {"name": "Imran Khan", "override_rating": 1.2, "confidence": 0.78, "accept_recommendation_bias": 0.62},
    {"name": "Ritu Sharma", "override_rating": 0.95, "confidence": 0.57, "accept_recommendation_bias": 0.48},
    {"name": "Manoj Das", "override_rating": 1.05, "confidence": 0.71, "accept_recommendation_bias": 0.55},
    {"name": "Kiran Patel", "override_rating": 1.0, "confidence": 0.68, "accept_recommendation_bias": 0.57},
] + [
    {
        "name": f"Ops Driver {i:03d}",
        "override_rating": round(0.85 + (i % 7) * 0.05, 2),
        "confidence": round(0.52 + (i % 5) * 0.06, 2),
        "accept_recommendation_bias": round(0.48 + (i % 6) * 0.04, 2),
    }
    for i in range(1, 155)
]


SCENARIO_PRESETS = [
    {
        "scenario_key": "warehouse_overflow_chennai",
        "name": "Warehouse Overflow Risk",
        "description": "Chennai public health warehouse nears capacity due to delayed unloading and high inbound medicine flow.",
        "event_city": "Chennai",
        "event_type": "warehouse_overflow",
        "severity": 0.72,
        "eta_multiplier": 1.18,
        "inventory_pressure_pct": 20.0,
    },
    {
        "scenario_key": "heavy_rain_corridor",
        "name": "Heavy Rainfall Corridor Slowdown",
        "description": "Severe rain impacts interstate corridors and raises route ETA multipliers for health and food deliveries.",
        "event_city": "Bengaluru",
        "event_type": "heavy_rainfall",
        "severity": 0.66,
        "eta_multiplier": 1.34,
        "inventory_pressure_pct": 8.0,
    },
    {
        "scenario_key": "road_blockage_strike",
        "name": "Road Blockage And Strike",
        "description": "A sudden labor strike and road blockade forces rerouting to protect critical deliveries.",
        "event_city": "Mumbai",
        "event_type": "road_blockage",
        "severity": 0.79,
        "eta_multiplier": 1.41,
        "inventory_pressure_pct": 14.0,
    },
]


def _seed_scenario_presets(session: Session) -> None:
    existing = {
        item.scenario_key
        for item in session.scalars(select(ScenarioPreset).where(ScenarioPreset.active.is_(True))).all()
    }
    to_add = [
        ScenarioPreset(**scenario)
        for scenario in SCENARIO_PRESETS
        if scenario["scenario_key"] not in existing
    ]
    if not to_add:
        return
    session.add_all(to_add)
    session.commit()


def seed_demo_data(session: Session) -> None:
    if session.scalar(select(Facility.id).limit(1)) is not None:
        _seed_scenario_presets(session)
        return

    session.add_all(Facility(**facility) for facility in FACILITY_SEEDS)
    session.add_all(DriverProfile(**driver) for driver in DRIVER_SEEDS)
    session.flush()

    facilities = {facility.name: facility for facility in session.scalars(select(Facility)).all()}
    drivers = session.scalars(select(DriverProfile)).all()

    vehicles = []
    legacy_vehicle_specs = [
        ("DL-MED", "Delhi National Medical Reserve", 1000, 0),
        ("DL-MED", "Delhi National Medical Reserve", 1000, 1),
        ("DL-MED", "Delhi National Medical Reserve", 1000, 2),
        ("DL-MED", "Delhi National Medical Reserve", 1000, 3),
        ("HS-REL", "Hosur Mobility Support Hub", 850, 4),
        ("HS-REL", "Hosur Mobility Support Hub", 850, 5),
        ("HS-REL", "Hosur Mobility Support Hub", 850, 0),
        ("SR-FOOD", "Surat Community Food Reserve", 900, 1),
        ("SR-FOOD", "Surat Community Food Reserve", 900, 2),
        ("NG-AID", "Nagpur Central Emergency Depot", 950, 3),
        ("NG-AID", "Nagpur Central Emergency Depot", 950, 4),
        ("BG-VAX", "Bengaluru Emergency Distribution Campus", 800, 5),
    ]
    for index, (prefix, home_name, payload, driver_idx) in enumerate(legacy_vehicle_specs, start=1):
        home = facilities[home_name]
        vehicles.append(
            Vehicle(
                identifier=f"{prefix}-{index:03d}",
                payload_capacity_units=payload,
                home_facility_id=home.id,
                current_facility_id=home.id,
                driver_profile_id=drivers[driver_idx % len(drivers)].id,
                average_speed_kmph=45 + (index % 4) * 3,
                emission_kg_per_km=1.35 + (index % 3) * 0.15,
            )
        )

    hub_facilities = [
        "Delhi National Medical Reserve",
        "Hosur Mobility Support Hub",
        "Surat Community Food Reserve",
        "Nagpur Central Emergency Depot",
        "Bengaluru Emergency Distribution Campus",
        "Chennai Public Health Warehouse",
        "Mumbai Coastal Relief Warehouse",
        "Kolkata Humanitarian Gateway",
        "Hyderabad Health Supply Connector",
        "Ahmedabad Vaccine Cold Store",
        "Jaipur Relief Consolidation Hub",
        "Pune Oxygen Buffer Center",
        "Lucknow Regional Depot",
        "Kanpur Logistics Hub",
        "Patna Emergency Store",
        "Ranchi Aid Center",
        "Bhubaneswar Food Buffer",
        "Guwahati Northeast Hub",
        "Chandigarh Northern Gateway",
        "Varanasi Distribution Hub",
    ]

    existing_identifiers = {v.identifier for v in vehicles}
    for index in range(13, 261):
        home_name = hub_facilities[index % len(hub_facilities)]
        home = facilities[home_name]
        capacity = 700 + (index % 8) * 75
        speed = 40 + (index % 6) * 4
        emission = 1.1 + (index % 5) * 0.12
        identifier = f"OPS-{index:04d}"
        while identifier in existing_identifiers:
            index += 1
            identifier = f"OPS-{index:04d}"
        existing_identifiers.add(identifier)

        vehicles.append(
            Vehicle(
                identifier=identifier,
                payload_capacity_units=capacity,
                home_facility_id=home.id,
                current_facility_id=home.id,
                driver_profile_id=drivers[index % len(drivers)].id,
                average_speed_kmph=speed,
                emission_kg_per_km=round(emission, 2),
            )
        )

    session.add_all(vehicles)
    session.flush()

    vehicle_map = {vehicle.identifier: vehicle for vehicle in vehicles}
    objectives = [
        Objective(
            name="Medical Equipment Bhopal to Lucknow",
            commodity="Medical Equipment",
            origin_facility_id=facilities["Bhopal Distribution Reserve"].id,
            destination_facility_id=facilities["Lucknow Regional Depot"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Vaccines Lucknow to Kanpur",
            commodity="Vaccines",
            origin_facility_id=facilities["Lucknow Regional Depot"].id,
            destination_facility_id=facilities["Kanpur Logistics Hub"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Relief Kits Patna to Ranchi",
            commodity="Relief Kits",
            origin_facility_id=facilities["Patna Emergency Store"].id,
            destination_facility_id=facilities["Ranchi Aid Center"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Food Grains Ranchi to Bhubaneswar",
            commodity="Food Grains",
            origin_facility_id=facilities["Ranchi Aid Center"].id,
            destination_facility_id=facilities["Bhubaneswar Food Buffer"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Medical Supplies Bhubaneswar to Visakhapatnam",
            commodity="Medical Supplies",
            origin_facility_id=facilities["Bhubaneswar Food Buffer"].id,
            destination_facility_id=facilities["Visakhapatnam Deepwater Port"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Agricultural Supplies Guwahati to Kolkata",
            commodity="Agricultural Supplies",
            origin_facility_id=facilities["Guwahati Northeast Hub"].id,
            destination_facility_id=facilities["Kolkata Humanitarian Gateway"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Winter Apparel Srinagar to Chandigarh",
            commodity="Winter Apparel",
            origin_facility_id=facilities["Srinagar Hill Reserve"].id,
            destination_facility_id=facilities["Chandigarh Northern Gateway"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Oxygen Cylinders Dehradun to Ludhiana",
            commodity="Oxygen Cylinders",
            origin_facility_id=facilities["Dehradun Supply Base"].id,
            destination_facility_id=facilities["Ludhiana Industrial Depot"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Relief Blankets Amritsar to Jodhpur",
            commodity="Relief Blankets",
            origin_facility_id=facilities["Amritsar Border Facility"].id,
            destination_facility_id=facilities["Jodhpur Arid Buffer"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Shelter Materials Jodhpur to Udaipur",
            commodity="Shelter Materials",
            origin_facility_id=facilities["Jodhpur Arid Buffer"].id,
            destination_facility_id=facilities["Udaipur Transfer Point"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Consumer Goods Udaipur to Vadodara",
            commodity="Consumer Goods",
            origin_facility_id=facilities["Udaipur Transfer Point"].id,
            destination_facility_id=facilities["Vadodara Transit Hub"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Processed Foods Rajkot to Kandla",
            commodity="Processed Foods",
            origin_facility_id=facilities["Rajkot Coastal Backup"].id,
            destination_facility_id=facilities["Kandla Export Port"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Fertilizers Bikaner to Jaipur",
            commodity="Fertilizers",
            origin_facility_id=facilities["Bikaner Sand Area Store"].id,
            destination_facility_id=facilities["Jaipur Relief Consolidation Hub"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Fresh Produce Nashik to Mumbai",
            commodity="Fresh Produce",
            origin_facility_id=facilities["Nashik Central Support"].id,
            destination_facility_id=facilities["Mumbai Relief Port Terminal"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Oxygen Cylinders Aurangabad to Pune",
            commodity="Oxygen Cylinders",
            origin_facility_id=facilities["Aurangabad Midpoint Center"].id,
            destination_facility_id=facilities["Pune Oxygen Buffer Center"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Medical Equipment Solapur to Kolhapur",
            commodity="Medical Equipment",
            origin_facility_id=facilities["Solapur Transit Base"].id,
            destination_facility_id=facilities["Kolhapur South Connect"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Food Grains Hubli to Mormugao",
            commodity="Food Grains",
            origin_facility_id=facilities["Hubli Cargo Relay"].id,
            destination_facility_id=facilities["Mormugao Bulk Port"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Seafood Mangaluru to Kochi",
            commodity="Seafood",
            origin_facility_id=facilities["Mangaluru Coastal Port"].id,
            destination_facility_id=facilities["Kochi Gateway Port"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Emergency Medicines Mysuru to Bengaluru",
            commodity="Emergency Medicines",
            origin_facility_id=facilities["Mysuru Southern Depot"].id,
            destination_facility_id=facilities["Bengaluru Emergency Distribution Campus"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Spices Thiruvananthapuram to Kochi",
            commodity="Spices",
            origin_facility_id=facilities["Thiruvananthapuram Southern Terminal"].id,
            destination_facility_id=facilities["Kochi Gateway Port"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Textile Yarn Tiruchirappalli to Madurai",
            commodity="Textile Yarn",
            origin_facility_id=facilities["Tiruchirappalli Crossroads"].id,
            destination_facility_id=facilities["Madurai Inner Station"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Hygiene Kits Madurai to Tuticorin",
            commodity="Hygiene Kits",
            origin_facility_id=facilities["Madurai Inner Station"].id,
            destination_facility_id=facilities["Tuticorin Marine Port"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Emergency Medicines Delhi to Chennai Flood Relief (Stockout Risk)",
            commodity="Emergency Medicines",
            origin_facility_id=facilities["Delhi National Medical Reserve"].id,
            destination_facility_id=facilities["Chennai Public Health Warehouse"].id,
            dispatch_interval_minutes=90,
            loading_duration_minutes=25,
            unloading_duration_minutes=40,
            sla_minutes=1080,
            priority=4,
            assigned_vehicle_ids=[
                vehicle_map["DL-MED-001"].id,
                vehicle_map["DL-MED-002"].id,
                vehicle_map["DL-MED-003"].id,
                vehicle_map["DL-MED-004"].id,
            ],
            fallback_facility_ids=[
                facilities["Bengaluru Emergency Distribution Campus"].id,
                facilities["Chennai Humanitarian Port"].id,
            ],
        ),
        Objective(
            name="Relief Kits Hosur to Mumbai Response Port",
            commodity="Disaster Relief Kits",
            origin_facility_id=facilities["Hosur Mobility Support Hub"].id,
            destination_facility_id=facilities["Mumbai Relief Port Terminal"].id,
            dispatch_interval_minutes=130,
            loading_duration_minutes=20,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[
                vehicle_map["HS-REL-005"].id,
                vehicle_map["HS-REL-006"].id,
                vehicle_map["HS-REL-007"].id,
            ],
            fallback_facility_ids=[
                facilities["Mumbai Coastal Relief Warehouse"].id,
                facilities["Surat Coastal Aid Jetty"].id,
            ],
        ),
        Objective(
            name="Food Grains Surat to Chennai Public Distribution",
            commodity="Food Grains",
            origin_facility_id=facilities["Surat Community Food Reserve"].id,
            destination_facility_id=facilities["Chennai Public Health Warehouse"].id,
            dispatch_interval_minutes=150,
            loading_duration_minutes=30,
            unloading_duration_minutes=35,
            sla_minutes=1800,
            priority=2,
            assigned_vehicle_ids=[
                vehicle_map["SR-FOOD-008"].id,
                vehicle_map["SR-FOOD-009"].id,
            ],
            fallback_facility_ids=[
                facilities["Mumbai Relief Port Terminal"].id,
                facilities["Bengaluru Emergency Distribution Campus"].id,
            ],
        ),
        Objective(
            name="Vaccines Nagpur to Kolkata Care Network",
            commodity="Vaccines",
            origin_facility_id=facilities["Nagpur Central Emergency Depot"].id,
            destination_facility_id=facilities["Kolkata Aid Dock Operations"].id,
            dispatch_interval_minutes=165,
            loading_duration_minutes=28,
            unloading_duration_minutes=38,
            sla_minutes=1560,
            priority=3,
            assigned_vehicle_ids=[
                vehicle_map["NG-AID-010"].id,
                vehicle_map["NG-AID-011"].id,
                vehicle_map["BG-VAX-012"].id,
            ],
            fallback_facility_ids=[
                facilities["Kharagpur Rail Relief Buffer"].id,
                facilities["Kolkata Humanitarian Gateway"].id,
            ],
        ),
        Objective(
            name="Grains Varanasi to Patna Reserve",
            commodity="Grains",
            origin_facility_id=facilities["Varanasi Distribution Hub"].id,
            destination_facility_id=facilities["Patna Emergency Store"].id,
            dispatch_interval_minutes=180,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Electronics Agra to Delhi Hub",
            commodity="Electronics",
            origin_facility_id=facilities["Agra Logistics Depot"].id,
            destination_facility_id=facilities["Delhi National Medical Reserve"].id,
            dispatch_interval_minutes=150,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Medical Supplies Prayagraj to Jabalpur",
            commodity="Medical Supplies",
            origin_facility_id=facilities["Prayagraj Relief Base"].id,
            destination_facility_id=facilities["Jabalpur Central Node"].id,
            dispatch_interval_minutes=200,
            loading_duration_minutes=25,
            unloading_duration_minutes=25,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Industrial Goods Vijayawada to Chennai",
            commodity="Industrial Goods",
            origin_facility_id=facilities["Vijayawada Transit Hub"].id,
            destination_facility_id=facilities["Chennai Public Health Warehouse"].id,
            dispatch_interval_minutes=140,
            loading_duration_minutes=35,
            unloading_duration_minutes=35,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Export Goods Nellore to Krishnapatnam",
            commodity="Export Goods",
            origin_facility_id=facilities["Nellore Coastal Depot"].id,
            destination_facility_id=facilities["Krishnapatnam Deep Port"].id,
            dispatch_interval_minutes=90,
            loading_duration_minutes=20,
            unloading_duration_minutes=40,
            sla_minutes=720,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Textiles Salem to Coimbatore",
            commodity="Textiles",
            origin_facility_id=facilities["Salem Industrial Gateway"].id,
            destination_facility_id=facilities["Coimbatore Nutrition Support Terminal"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1080,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Raw Cotton Erode to Tiruppur",
            commodity="Raw Cotton",
            origin_facility_id=facilities["Erode Textile Buffer"].id,
            destination_facility_id=facilities["Tiruppur Export Hub"].id,
            dispatch_interval_minutes=100,
            loading_duration_minutes=25,
            unloading_duration_minutes=25,
            sla_minutes=720,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Finished Garments Tiruppur to Ennore Port",
            commodity="Finished Garments",
            origin_facility_id=facilities["Tiruppur Export Hub"].id,
            destination_facility_id=facilities["Ennore Container Port"].id,
            dispatch_interval_minutes=180,
            loading_duration_minutes=40,
            unloading_duration_minutes=60,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="First Aid Kits Belagavi to Hubli",
            commodity="First Aid Kits",
            origin_facility_id=facilities["Belagavi Border Node"].id,
            destination_facility_id=facilities["Hubli Cargo Relay"].id,
            dispatch_interval_minutes=150,
            loading_duration_minutes=45,
            unloading_duration_minutes=45,
            sla_minutes=1080,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Water Purification Tablets Jamnagar to Dahej",
            commodity="Water Purification Tablets",
            origin_facility_id=facilities["Jamnagar Petro-Logistics Base"].id,
            destination_facility_id=facilities["Dahej Chemical Port"].id,
            dispatch_interval_minutes=160,
            loading_duration_minutes=40,
            unloading_duration_minutes=40,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Fuel for Generators Dhanbad to Jamshedpur",
            commodity="Fuel for Generators",
            origin_facility_id=facilities["Dhanbad Mining Relief Center"].id,
            destination_facility_id=facilities["Jamshedpur Steel City Depot"].id,
            dispatch_interval_minutes=120,
            loading_duration_minutes=35,
            unloading_duration_minutes=35,
            sla_minutes=1080,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Structural Relief Materials Jamshedpur to Haldia",
            commodity="Structural Relief Materials",
            origin_facility_id=facilities["Jamshedpur Steel City Depot"].id,
            destination_facility_id=facilities["Haldia Industrial Port"].id,
            dispatch_interval_minutes=180,
            loading_duration_minutes=50,
            unloading_duration_minutes=50,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Tea Siliguri to Guwahati",
            commodity="Tea",
            origin_facility_id=facilities["Siliguri Northeast Gateway"].id,
            destination_facility_id=facilities["Guwahati Northeast Hub"].id,
            dispatch_interval_minutes=150,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Essentials Agartala to Shillong",
            commodity="Essentials",
            origin_facility_id=facilities["Agartala Frontier Store"].id,
            destination_facility_id=facilities["Shillong Hill Base"].id,
            dispatch_interval_minutes=240,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=2160,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Winter Supplies Jammu to Srinagar",
            commodity="Winter Supplies",
            origin_facility_id=facilities["Jammu Northern Terminal"].id,
            destination_facility_id=facilities["Srinagar Hill Reserve"].id,
            dispatch_interval_minutes=180,
            loading_duration_minutes=40,
            unloading_duration_minutes=40,
            sla_minutes=1440,
            priority=1,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Marine Goods Bhavnagar to Mundra Port",
            commodity="Marine Goods",
            origin_facility_id=facilities["Bhavnagar Gulf Depot"].id,
            destination_facility_id=facilities["Mundra Mega Port"].id,
            dispatch_interval_minutes=200,
            loading_duration_minutes=35,
            unloading_duration_minutes=45,
            sla_minutes=1440,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Sanitizers Dahej Port to Ahmedabad",
            commodity="Sanitizers",
            origin_facility_id=facilities["Dahej Chemical Port"].id,
            destination_facility_id=facilities["Ahmedabad Vaccine Cold Store"].id,
            dispatch_interval_minutes=160,
            loading_duration_minutes=30,
            unloading_duration_minutes=30,
            sla_minutes=1440,
            priority=3,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
        Objective(
            name="Imported Medicines Mundra Port to Jaipur Hub",
            commodity="Imported Medicines",
            origin_facility_id=facilities["Mundra Mega Port"].id,
            destination_facility_id=facilities["Jaipur Relief Consolidation Hub"].id,
            dispatch_interval_minutes=220,
            loading_duration_minutes=45,
            unloading_duration_minutes=45,
            sla_minutes=1800,
            priority=2,
            assigned_vehicle_ids=[],
            fallback_facility_ids=[],
        ),
    ]
    session.add_all(objectives)
    session.flush()

    objective_by_name = {objective.name: objective for objective in objectives}
    objective_assignments = {
        "DL-MED-001": "Emergency Medicines Delhi to Chennai Flood Relief (Stockout Risk)",
        "DL-MED-002": "Emergency Medicines Delhi to Chennai Flood Relief (Stockout Risk)",
        "DL-MED-003": "Emergency Medicines Delhi to Chennai Flood Relief (Stockout Risk)",
        "DL-MED-004": "Emergency Medicines Delhi to Chennai Flood Relief (Stockout Risk)",
        "HS-REL-005": "Relief Kits Hosur to Mumbai Response Port",
        "HS-REL-006": "Relief Kits Hosur to Mumbai Response Port",
        "HS-REL-007": "Relief Kits Hosur to Mumbai Response Port",
        "SR-FOOD-008": "Food Grains Surat to Chennai Public Distribution",
        "SR-FOOD-009": "Food Grains Surat to Chennai Public Distribution",
        "NG-AID-010": "Vaccines Nagpur to Kolkata Care Network",
        "NG-AID-011": "Vaccines Nagpur to Kolkata Care Network",
        "BG-VAX-012": "Vaccines Nagpur to Kolkata Care Network",
    }
    for vehicle_id, objective_name in objective_assignments.items():
        vehicle_map[vehicle_id].default_objective_id = objective_by_name[objective_name].id

    port_links = [
        PortLink(
            warehouse_id=facilities["Chennai Public Health Warehouse"].id,
            port_id=facilities["Chennai Humanitarian Port"].id,
            reserved_capacity_units=1400,
            spillover_threshold_pct=78,
            max_spillover_units=1800,
        ),
        PortLink(
            warehouse_id=facilities["Mumbai Coastal Relief Warehouse"].id,
            port_id=facilities["Mumbai Relief Port Terminal"].id,
            reserved_capacity_units=1500,
            spillover_threshold_pct=75,
            max_spillover_units=2000,
        ),
        PortLink(
            warehouse_id=facilities["Kolkata Humanitarian Gateway"].id,
            port_id=facilities["Kolkata Aid Dock Operations"].id,
            reserved_capacity_units=1200,
            spillover_threshold_pct=80,
            max_spillover_units=1600,
        ),
        PortLink(
            warehouse_id=facilities["Surat Community Food Reserve"].id,
            port_id=facilities["Surat Coastal Aid Jetty"].id,
            reserved_capacity_units=900,
            spillover_threshold_pct=76,
            max_spillover_units=1300,
        ),
        PortLink(
            warehouse_id=facilities["Jamshedpur Steel City Depot"].id,
            port_id=facilities["Haldia Industrial Port"].id,
            reserved_capacity_units=1800,
            spillover_threshold_pct=70,
            max_spillover_units=2500,
        ),
        PortLink(
            warehouse_id=facilities["Tiruppur Export Hub"].id,
            port_id=facilities["Ennore Container Port"].id,
            reserved_capacity_units=2000,
            spillover_threshold_pct=75,
            max_spillover_units=3000,
        ),
        PortLink(
            warehouse_id=facilities["Jamnagar Petro-Logistics Base"].id,
            port_id=facilities["Dahej Chemical Port"].id,
            reserved_capacity_units=1600,
            spillover_threshold_pct=72,
            max_spillover_units=2200,
        ),
        PortLink(
            warehouse_id=facilities["Jaipur Relief Consolidation Hub"].id,
            port_id=facilities["Mundra Mega Port"].id,
            reserved_capacity_units=2500,
            spillover_threshold_pct=80,
            max_spillover_units=3500,
        ),
        PortLink(
            warehouse_id=facilities["Nellore Coastal Depot"].id,
            port_id=facilities["Krishnapatnam Deep Port"].id,
            reserved_capacity_units=1400,
            spillover_threshold_pct=78,
            max_spillover_units=1800,
        ),
        PortLink(
            warehouse_id=facilities["Rajkot Coastal Backup"].id,
            port_id=facilities["Pipavav Private Port"].id,
            reserved_capacity_units=1200,
            spillover_threshold_pct=74,
            max_spillover_units=1600,
        ),
    ]
    session.add_all(port_links)
    session.commit()
    _seed_scenario_presets(session)
